# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a698bd5e2460e725a8669f93012e992d9f0ac48058777c07c69e9ed02ff57b41a83612f64852774c7fd6295a9b18c700ab97a58d53e6a2a77aaa16c33fe550f0

test:
  secret_key_base: a7cb31bde68bc871be7d818f8a6a61be081329e7f6d9df577c9a9a65cc157068f4c252d7a46fc6e785259e098a9792eeb463296701ca28488478d452b5656f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
